#tri_selection

In [4]:
from random import *
def list_aleat(n):
	S = [0]*n
	for i in range(n):
		S[i] = randrange(1,1000)
	return S


def tri_selection(T):
	for i in range(0, len(T)-1):
		MIN = T[i]
		indice = i
		for j in range(i+1, len(T)):
			if T[j] < MIN :
			  MIN = T[j]
			  indice = j
		tmp = T[i]
		T[i] = T[indice]
		T[indice] = tmp

#programme principal
tab1 = list_aleat(20)
print("le tableau non trie : \n", tab1)
#tri par selection
tri_selection(tab1)
print("le tableau trie : \n", tab1)

le tableau non trie :
 [79, 480, 216, 295, 251, 217, 752, 713, 592, 385, 54, 766, 905, 340, 233, 431, 323, 647, 471, 319]
le tableau trie :
 [54, 79, 216, 217, 233, 251, 295, 319, 323, 340, 385, 431, 471, 480, 592, 647, 713, 752, 766, 905]